<?php

namespace Xanadu\SeguridadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosHasPermisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
    public function recuperarPassword($usuario)
    {
        $dql = "SELECT u.password FROM XanaduSeguridadBundle:Usuarios u WHERE u.id = :usuario";
        $consulta = $this->getEntityManager()->createQuery($dql)
                ->setParameter("usuario", $usuario);
        
        return $consulta->getSingleScalarResult();
    }
}
