<?php

namespace Xanadu\SeguridadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosHasPermisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosHasPermisosRepository extends EntityRepository
{
}
